### ISSUE TITLE
Cannot connect to plex

### ISSUE THREAD

**Issue by Dexxa1024** [itsToggle/plex_rd#3]
Hi

I've tried to install the rclone.exe on windows and nothing loaded,  and i got plex_rd working, which is saying cannot reach plex even tho i have it on the same server, Any ideas to get rclone installed and for it to access my plex? Im using windows server 2012 :-)

**Comment by Dexxa1024** [comment]
C:\Users\dexxa\Downloads\plex_rd-main>python plex_rd.py
Traceback (most recent call last):
  File "C:\Users\dexxa\Downloads\plex_rd-main\plex_rd.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by itsToggle** [comment]
Hey,

Could you go into a bit more detail on why rclone couldnt be installed?

As for the plex error, it is most likely a misconfiguration of one of the plex users you provided. Have you checked if the token youve provided for the plex user(s) works?

**Comment by Dexxa1024** [comment]
Hey

some how i got rclone to work just had to run it in cmd by tryping cd downloads and then typing rclone config

and i set that up with my real de api token   and then tried mounting the drive on windows with rclone cmount dex: v thats if i got it right 

for plex api i went into a movie and then get info and then xml and got it from the url, I've tried the main ip, my internal ip and 127.0.0.1 

I have added a screen shot so you can see if im doing something wrong, as im a noob at cmd lol
![plex1](https://user-images.githubusercontent.com/11196220/169694654-66f50a6d-ad4b-44dd-8289-976bc03c233a.png)

**Comment by itsToggle** [comment]
looks good so far. Youve got the correct token. Try the address: "http://localhost:32400"

**Comment by Dexxa1024** [comment]
Tried that address in the browser and it loaded plex, tried it on the plexrd and still says could not reach plex :-(

**Comment by itsToggle** [comment]
Could you perhaps try again with the latest version?
Ive added a debug mode, which will print more useful information so we can find the problem together.

To enable it, go to '2) Settings' - '5) Debug' - '1) Debug printing' - '1) Edit' and type "true".

When you now run the script, error messages should be printed. Please show them to me, if they dont contain sensitive information :)

**Comment by Dexxa1024** [comment]
Hmmm i downloaded the new one, and entered the same details, and it seems to be working

I have added a screenshot to show you

I added a watchlist on plex from the discover part, but nothings happening yet, do i need another program to install to install the torrents on to real debrid?
![plex2](https://user-images.githubusercontent.com/11196220/169702656-66f502fc-f833-4aa4-a3cf-e2da02d67bb6.png)

**Comment by itsToggle** [comment]
There are no errors logged. Are you sure you've turned on the debug printing? Make sure you've typed "true" without the quotation marks.
The Plex Watchlist should only be updated entirely every 30 Minutes - something must produce errors.

**Comment by Dexxa1024** [comment]
oops silly me, did it and forgot to click 0 to save lol

Its now on
![plex3](https://user-images.githubusercontent.com/11196220/169705002-856fb81f-88c8-4cb5-baf5-058e7ef70200.png)

**Comment by itsToggle** [comment]
Okay the 401 error suggests that the Plex token isnt working. You could open plex.tv/devices.xml and pick a different token from one of the listed devices. Try it again with that one.

**Comment by Dexxa1024** [comment]
Everytime i go into users part of the plexrd and click edit, the box just closes :-S

**Comment by Dexxa1024** [comment]
edited the json file, and it looks like its working now :-D Thank you

**Comment by itsToggle** [comment]
Nice!
